# Generated by Django 4.2.20 on 2025-05-03 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
