# Generated by Django 4.2.20 on 2025-05-03 00:29

import core.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_comment', '0001_initial'),
        ('core_user', '0003_user_post_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='post_liked',
            new_name='posts_liked',
        ),
        migrations.AddField(
            model_name='user',
            name='comments_liked',
            field=models.ManyToManyField(related_name='commented_by', to='core_comment.comment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.user.models.user_directory_path),
        ),
    ]
